// ── VOCABULARY ──────────────────────────────────────────────────────────────
// level 1 = easy (single syllable, very common)      → ages 5–8
// level 2 = harder (extra single chars + two-char words) → ages 7–10+
// level 3 = hardest (less common two/three-char words)   → ages 9–10+
const vocab = [
    // Numbers
    { char:'一', pinyin:'yī',       meaning:'one',          level:1 },
    { char:'二', pinyin:'èr',       meaning:'two',          level:1 },
    { char:'三', pinyin:'sān',      meaning:'three',        level:1 },
    { char:'四', pinyin:'sì',       meaning:'four',         level:1 },
    { char:'五', pinyin:'wǔ',       meaning:'five',         level:1 },
    { char:'六', pinyin:'liù',      meaning:'six',          level:1 },
    { char:'七', pinyin:'qī',       meaning:'seven',        level:1 },
    { char:'八', pinyin:'bā',       meaning:'eight',        level:1 },
    { char:'九', pinyin:'jiǔ',      meaning:'nine',         level:1 },
    { char:'十', pinyin:'shí',      meaning:'ten',          level:1 },
    // Pronouns
    { char:'你', pinyin:'nǐ',       meaning:'you',          level:1 },
    { char:'我', pinyin:'wǒ',       meaning:'I / me',       level:1 },
    { char:'他', pinyin:'tā',       meaning:'he',           level:1 },
    { char:'她', pinyin:'tā',       meaning:'she',          level:1 },
    // Adjectives
    { char:'好', pinyin:'hǎo',      meaning:'good',         level:1 },
    { char:'大', pinyin:'dà',       meaning:'big',          level:1 },
    { char:'小', pinyin:'xiǎo',     meaning:'small',        level:1 },
    { char:'多', pinyin:'duō',      meaning:'many',         level:1 },
    { char:'少', pinyin:'shǎo',     meaning:'few',          level:1 },
    { char:'热', pinyin:'rè',       meaning:'hot',          level:1 },
    { char:'冷', pinyin:'lěng',     meaning:'cold',         level:1 },
    { char:'新', pinyin:'xīn',      meaning:'new',          level:2 },
    // Verbs
    { char:'吃', pinyin:'chī',      meaning:'eat',          level:1 },
    { char:'喝', pinyin:'hē',       meaning:'drink',        level:1 },
    { char:'来', pinyin:'lái',      meaning:'come',         level:1 },
    { char:'去', pinyin:'qù',       meaning:'go',           level:1 },
    { char:'看', pinyin:'kàn',      meaning:'look / watch', level:1 },
    { char:'听', pinyin:'tīng',     meaning:'listen',       level:1 },
    { char:'坐', pinyin:'zuò',      meaning:'sit',          level:1 },
    { char:'说', pinyin:'shuō',     meaning:'speak',        level:2 },
    { char:'读', pinyin:'dú',       meaning:'read aloud',   level:2 },
    { char:'写', pinyin:'xiě',      meaning:'write',        level:2 },
    { char:'买', pinyin:'mǎi',      meaning:'buy',          level:2 },
    { char:'住', pinyin:'zhù',      meaning:'live',         level:2 },
    { char:'叫', pinyin:'jiào',     meaning:'be called',    level:2 },
    { char:'有', pinyin:'yǒu',      meaning:'have',         level:2 },
    { char:'是', pinyin:'shì',      meaning:'to be',        level:2 },
    // Single-char nouns
    { char:'人', pinyin:'rén',      meaning:'person',       level:1 },
    { char:'书', pinyin:'shū',      meaning:'book',         level:1 },
    { char:'水', pinyin:'shuǐ',     meaning:'water',        level:1 },
    { char:'茶', pinyin:'chá',      meaning:'tea',          level:1 },
    { char:'猫', pinyin:'māo',      meaning:'cat',          level:1 },
    { char:'狗', pinyin:'gǒu',      meaning:'dog',          level:1 },
    { char:'家', pinyin:'jiā',      meaning:'home',         level:1 },
    { char:'月', pinyin:'yuè',      meaning:'month',        level:1 },
    { char:'日', pinyin:'rì',       meaning:'day',          level:1 },
    { char:'鱼', pinyin:'yú',       meaning:'fish',         level:1 },
    { char:'花', pinyin:'huā',      meaning:'flower',       level:1 },
    { char:'钱', pinyin:'qián',     meaning:'money',        level:2 },
    { char:'字', pinyin:'zì',       meaning:'character',    level:2 },
    { char:'年', pinyin:'nián',     meaning:'year',         level:2 },
    // Family + greetings (very common two-char words)
    { char:'你好',  pinyin:'nǐ hǎo',    meaning:'hello',     level:1 },
    { char:'谢谢',  pinyin:'xiè xie',   meaning:'thank you', level:1 },
    { char:'再见',  pinyin:'zài jiàn',  meaning:'goodbye',   level:1 },
    { char:'妈妈',  pinyin:'mā ma',     meaning:'mom',       level:1 },
    { char:'爸爸',  pinyin:'bà ba',     meaning:'dad',       level:1 },
    // Harder two-char compounds
    { char:'老师',  pinyin:'lǎo shī',   meaning:'teacher',   level:2 },
    { char:'学生',  pinyin:'xué sheng', meaning:'student',   level:2 },
    { char:'朋友',  pinyin:'péng you',  meaning:'friend',    level:2 },
    { char:'苹果',  pinyin:'píng guǒ',  meaning:'apple',     level:2 },
    { char:'米饭',  pinyin:'mǐ fàn',    meaning:'rice',      level:2 },
    { char:'今天',  pinyin:'jīn tiān',  meaning:'today',     level:2 },
    { char:'明天',  pinyin:'míng tiān', meaning:'tomorrow',  level:2 },
    { char:'昨天',  pinyin:'zuó tiān',  meaning:'yesterday', level:2 },
    { char:'高兴',  pinyin:'gāo xìng',  meaning:'happy',     level:2 },
    { char:'漂亮',  pinyin:'piào liang', meaning:'beautiful', level:2 },
    { char:'电话',  pinyin:'diàn huà',  meaning:'phone',     level:2 },
    { char:'学校',  pinyin:'xué xiào',  meaning:'school',    level:2 },
    { char:'中国',  pinyin:'Zhōng guó', meaning:'China',     level:2 },
    { char:'天气',  pinyin:'tiān qì',   meaning:'weather',   level:2 },
    { char:'工作',  pinyin:'gōng zuò',  meaning:'work',      level:2 },
    // Level 3 words
    { char:'喜欢',  pinyin:'xǐ huan',   meaning:'like',        level:3 },
    { char:'知道',  pinyin:'zhī dào',   meaning:'know',        level:3 },
    { char:'睡觉',  pinyin:'shuì jiào', meaning:'sleep',       level:3 },
    { char:'觉得',  pinyin:'jué de',    meaning:'feel / think',level:3 },
    { char:'准备',  pinyin:'zhǔn bèi',  meaning:'prepare',     level:3 },
    { char:'因为',  pinyin:'yīn wèi',   meaning:'because',     level:3 },
    { char:'所以',  pinyin:'suǒ yǐ',    meaning:'so',          level:3 },
    { char:'已经',  pinyin:'yǐ jīng',   meaning:'already',     level:3 },
    { char:'衣服',  pinyin:'yī fu',     meaning:'clothes',     level:3 },
    { char:'眼睛',  pinyin:'yǎn jing',  meaning:'eyes',        level:3 },
    { char:'医生',  pinyin:'yī shēng',  meaning:'doctor',      level:3 },
    { char:'医院',  pinyin:'yī yuàn',   meaning:'hospital',    level:3 },
    { char:'电脑',  pinyin:'diàn nǎo',  meaning:'computer',    level:3 },
    { char:'飞机',  pinyin:'fēi jī',    meaning:'airplane',    level:3 },
    { char:'火车',  pinyin:'huǒ chē',   meaning:'train',       level:3 },
    { char:'星期',  pinyin:'xīng qī',   meaning:'week',        level:3 },
    { char:'生日',  pinyin:'shēng rì',  meaning:'birthday',    level:3 },
    { char:'熊猫',  pinyin:'xióng māo', meaning:'panda',       level:3 },
    { char:'超市',  pinyin:'chāo shì',  meaning:'supermarket', level:3 },
    { char:'图书馆', pinyin:'tú shū guǎn', meaning:'library',     level:3 },
];
